<a href="https://colab.research.google.com/github/lwehausen/Python/blob/main/Convert_to_wide_long_formats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Generate random data that is in standard format, then convert it to wide format.

In [ ]:
import pandas as pd

In [ ]:
#First, generate the code to create the dataframe that will be converted to wide format:
data_long = pd.DataFrame(columns = ["grp", "sex", "meanL", "sdL", "meanR", "sdR"])
data_long.loc[0] = ["A", "F", 0.225, 0.106, 0.340, 0.0849]
data_long.loc[1] = ["A", "M", 0.470, 0.325, 0.570, 0.3250]
data_long.loc[2] = ["B", "F", 0.325, 0.106, 0.400, 0.0707]
data_long.loc[3] = ["B", "M", 0.547, 0.308, 0.647, 0.2740]
data_long

  grp sex  meanL    sdL  meanR     sdR
0   A   F  0.225  0.106  0.340  0.0849
1   A   M  0.470  0.325  0.570  0.3250
2   B   F  0.325  0.106  0.400  0.0707
3   B   M  0.547  0.308  0.647  0.2740

In [ ]:
#Now generate the code to convert the original dataframe to wide format:
pd.pivot(data_long, index = "grp", columns = "sex", values = ["meanL", "sdL", "meanR", "sdR"])

     meanL           sdL        meanR            sdR
sex      F      M      F      M     F      M       F      M
grp
A    0.225  0.470  0.106  0.325  0.34  0.570  0.0849  0.325
B    0.325  0.547  0.106  0.308  0.40  0.647  0.0707  0.274

Consider the pccc icd10 dataset.

In [28]:
pc = pd.read_csv("https://raw.githubusercontent.com/gjm112/DSCI401/main/data/pccc_icd10_dataset.csv")

Remove all the columns labeled with ”g” and a number.

In [29]:
#First, let's take a look at the data:
pc.head(1)

,id,dx1,dx2,dx3,dx4,dx5,dx6,dx7,dx8,dx9,...,g1,g2,g3,g4,g5,g6,g7,g8,g9,g10
0,1,S9410XS,I67841,E70339,NaN,S14121A,M66229,S92065G,O0973,NaN,...,239196.0,672832.0,683784.0,757546.0,NaN,168052.0,104625.0,NaN,850974.0,NaN

In [31]:
#Remove all the columns labeled with "g" and a number:
pc = pc.drop(columns=["g1", "g2", "g3", "g4", "g5", "g6", "g7", "g8", "g9", "g10"])

Now convert this to a long data set with three columns: id, type (pc or dx), and code.

In [32]:
#Go from wide to narrow
pd.melt(pc, id_vars = "id",
        value_vars = ["dx1", "dx2", "dx3", "dx4", "dx5", "dx6", "dx7", "dx8", "dx9", "dx10", "pc1", "pc2", "pc3", "pc4","pc5", "pc6", "pc7", "pc8", "pc9", "pc10"],
        value_name = "code",
        var_name = "type")

         id  type     code
0         1   dx1  S9410XS
1         2   dx1      NaN
2         3   dx1      NaN
3         4   dx1  S7226XK
4         5   dx1  S92246A
...     ...   ...      ...
19995   996  pc10  BR49ZZZ
19996   997  pc10  0T184KD
19997   998  pc10      NaN
19998   999  pc10  0N940ZZ
19999  1000  pc10  0NS5XZZ

[20000 rows x 3 columns]